const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalizeCategory=value=>String(value||'')==='Transportation & Parking'?'Transportation':String(value||'');
const departmentFor=b=>b.department||({'Administration & Governance':'Legislative Services','Animals':'Bylaw Services','Business & Licensing':'Business Licensing','Environment':'Engineering & Public Works','Finance':'Finance','Land Use & Zoning':'Development Services','Other':'Corporate Services','Parks & Recreation':'Parks, Recreation & Culture','Public Safety':'Public Safety','Transportation':'Engineering & Public Works'})[normalizeCategory(b.category)]||'Corporate Services';
let records=[];
const q=document.querySelector('#q'),cat=document.querySelector('#category'),status=document.querySelector('#status'),year=document.querySelector('#year'),department=document.querySelector('#department'),source=document.querySelector('#source'),list=document.querySelector('#list'),count=document.querySelector('#results-count');
function starButton(b){const watched=BylawWatchlist.has(b.number);return `<button class="watch-star${watched?' active':''}" type="button" data-watch-number="${esc(b.number)}" aria-pressed="${watched}" aria-label="${watched?'Remove':'Add'} ${esc(b.title)} ${watched?'from':'to'} watchlist" title="${watched?'Remove from':'Add to'} watchlist">${watched?'★':'☆'}</button>`}
function render(){const term=q.value.trim().toLowerCase(),params=new URLSearchParams(location.search),view=params.get('view')||params.get('status')||'';const text=b=>(`${b.number} ${b.title} ${b.description} ${b.category} ${b.status} ${b.legal_status||''} ${JSON.stringify(b.relationships||{})} ${b.year} ${departmentFor(b)} ${b.source||''}`).toLowerCase();const viewMatch=b=>view==='amended'
  ?(b.legal_status==='Amendment bylaw'||Boolean(b.relationships?.amends?.length))
  :view==='repealed'
    ?(['Repealed','Replaced'].includes(b.legal_status)
      ||Boolean(b.relationships?.repealed_by?.length)
      ||Boolean(b.relationships?.replaced_by?.length))
    :true;const rows=records.filter(b=>(!term||text(b).includes(term))&&(!cat.value||b.category===cat.value)&&(!status.value||b.status===status.value)&&(!year.value||String(b.year)===year.value)&&(!department.value||departmentFor(b)===department.value)&&(!source.value||b.source===source.value)&&viewMatch(b));count.textContent=`${rows.length} records shown`;list.innerHTML=rows.map(b=>`<article class="bylaw-row"><div class="bylaw-number">No. ${esc(b.number)}</div><div class="bylaw-row-copy"><h2>${starButton(b)}<a href="${esc(b.detail_url)}">${esc(b.title)}</a></h2><p>${esc(b.description)}</p><div class="bylaw-meta"><span class="meta-pill">${esc(b.category)}</span><span class="meta-pill">${esc(b.legal_status||b.status)}</span><span class="meta-pill">${esc(b.year||'Year unknown')}</span><span class="meta-pill">${esc(departmentFor(b))}</span></div></div><a class="secondary-button" href="${esc(b.detail_url)}">View details</a></article>`).join('')||'<p>No matching bylaws.</p>'}
list.addEventListener('click',event=>{const button=event.target.closest('[data-watch-number]');if(!button)return;BylawWatchlist.toggle(button.dataset.watchNumber);render()});window.addEventListener('bylaw-watchlist-change',render);
function fill(select,values){values.forEach(v=>select.add(new Option(v,v)))}
NanaimoData.fetch(`data/bylaws.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()).then(d=>{records=(Array.isArray(d)?d:(Array.isArray(d.bylaws)?d.bylaws:[])).map(record=>({...record,category:normalizeCategory(record.category)}));console.info('[Nanaimo Bylaw Tracker] loaded',records.length,'records from data/bylaws.json');document.querySelector('#data-note').textContent=`Connected dataset: ${records.length} official online records.`;fill(cat,[...new Set(records.map(x=>x.category).filter(Boolean))].sort());fill(status,[...new Set(records.map(x=>x.status).filter(Boolean))].sort());fill(year,[...new Set(records.map(x=>String(x.year||'')).filter(Boolean))].sort((a,b)=>Number(b)-Number(a)));fill(department,[...new Set(records.map(departmentFor))].sort());fill(source,[...new Set(records.map(x=>x.source).filter(Boolean))].sort());const p=new URLSearchParams(location.search);q.value=p.get('q')||'';for(const [el,key] of [[cat,'category'],[status,'status'],[year,'year'],[department,'department'],[source,'source']]){let requested=p.get(key)||'';if(key==='category')requested=normalizeCategory(requested);if(key==='status'&&['amended','repealed'].includes(requested.toLowerCase()))requested='';if(requested&&!Array.from(el.options).some(o=>o.value===requested))el.add(new Option(requested,requested));el.value=requested}render()}).catch(()=>{document.querySelector('#data-note').textContent='Could not load bylaw data.'});
[q,cat,status,year,department,source].forEach(el=>el.addEventListener('input',render));
