const C=window.CivicRecords;
const q=document.querySelector('#committee-q'),nameSel=document.querySelector('#committee-name'),decision=document.querySelector('#committee-decision'),year=document.querySelector('#committee-year'),hasPdf=document.querySelector('#committee-has-pdf'),results=document.querySelector('#committee-results'),count=document.querySelector('#committee-result-count'),directory=document.querySelector('#committee-directory');let items=[];
function populate(sel,vals,label){sel.innerHTML=`<option value="">${label}</option>`+vals.map(v=>`<option value="${C.escapeHtml(v)}">${C.escapeHtml(v)}</option>`).join('')}
function card(item){const local=C.localPdfPath(item.local_document),primary=C.primaryUrl(item,'../');return `<article class="council-item"><div class="council-item-meta"><span class="status amended">${C.escapeHtml(C.activityLabel(item))}</span><span>${C.escapeHtml(item.date||'Date unavailable')}</span><span>${C.escapeHtml(C.committeeName(item))}</span></div><h2>${C.link(primary,item.title||'Committee item')}</h2><p>${C.escapeHtml(item.summary||'')}</p><div class="council-item-links">${C.link(`detail.html?committee=${encodeURIComponent(C.slug(C.committeeName(item)))}`,'Committee page')}${C.link(C.safeExternalUrl(item.meeting_url),'Official meeting')}${C.link(local?C.viewerUrl(local,item,'../'):'','Archived PDF')}${!local?C.link(C.safeExternalUrl(item.source_document_url),'Source document'):''}</div></article>`}
function render(){const query=q.value.trim().toLowerCase();const filtered=items.filter(i=>{const hay=`${i.title||''} ${i.summary||''} ${i.number||''} ${i.action||''} ${C.committeeName(i)} ${i.date||''}`.toLowerCase();return(!query||hay.includes(query))&&(!nameSel.value||C.committeeName(i)===nameSel.value)&&(!decision.value||C.activityLabel(i)===decision.value)&&(!year.value||String(i.date||'').startsWith(year.value))&&(!hasPdf.checked||Boolean(C.localPdfPath(i.local_document)))});count.textContent=`${filtered.length.toLocaleString()} of ${items.length.toLocaleString()} items`;results.innerHTML=filtered.length?filtered.map(card).join(''):'<p class="empty-state">No committee records match these filters.</p>'}
function rows(payload){return Array.isArray(payload)?payload:(Array.isArray(payload?.items)?payload.items:[])}
async function committeeRows(){let fallback=[];for(const url of ['data/committee-items.json','data/council-items.json']){try{const r=await NanaimoData.fetch(url,{cache:'no-store'});if(!r.ok)continue;const loaded=rows(await r.json()).filter(item=>item&&typeof item==='object');if(url.includes('committee-items')){if(loaded.length)return loaded;continue}fallback=loaded.filter(item=>C.meetingGroup(item)==='committee')}catch(error){console.warn(`[Nanaimo Bylaw Tracker] ${url} unavailable`,error)}}return fallback}
async function load(){items=await committeeRows();if(!items.length)throw new Error('No committee records were found in either committee-items.json or council-items.json');const names=[...new Set(items.map(C.committeeName))].sort();populate(nameSel,names,'All committees and panels');populate(year,[...new Set(items.map(i=>String(i.date||'').slice(0,4)).filter(Boolean))].sort().reverse(),'All years');directory.innerHTML=names.map(n=>{const found=items.filter(i=>C.committeeName(i)===n);return `<a class="committee-directory-card" href="detail.html?committee=${encodeURIComponent(C.slug(n))}"><strong>${C.escapeHtml(n)}</strong><span>${found.length.toLocaleString()} items</span><small>${C.escapeHtml(found.map(i=>i.date).filter(Boolean).sort().reverse()[0]||'Date unavailable')}</small></a>`}).join('');render()}
load().catch(e=>{console.error('[Nanaimo Bylaw Tracker] committee page load failed',e);count.textContent='Data unavailable';results.innerHTML='<p class="empty-state">Committee records could not be loaded from the current cloud or local datasets.</p>';directory.innerHTML=''});[q,nameSel,decision,year,hasPdf].forEach(c=>c&&c.addEventListener('input',render));
